services:
  varen:
    container_name: varen
    deploy:
      resources:
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    image: denden047/varen
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:11.3.1-devel-ubuntu20.04
        - PYTHON_VERSION=3.8
        - FORCE_CUDA=1
        - UID=1002
        - GID=1002
        - USER_NAME=naoya
        - GROUP_NAME=naoya
        - TORCH_CUDA_ARCH_LIST=7.5
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/home/naoya/varen
      - /data/naoya/:/data/
    # ports:
    #   - 8000:8000